ALTER TABLE public.tickets
ADD COLUMN IF NOT EXISTS checkout_lat DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS checkout_lng DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS checkout_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS evidencia_antes_base64 TEXT,
ADD COLUMN IF NOT EXISTS evidencia_depois_base64 TEXT,
ADD COLUMN IF NOT EXISTS despesas_json JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS assinatura_datahora TIMESTAMP WITH TIME ZONE;

NOTIFY pgrst, 'reload schema';
